### ISSUE TITLE
Minified build is mangled

### ISSUE THREAD

**Issue by mourner** [jahting/pnltri.js#1]
https://github.com/jahting/pnltri.js/blob/master/build/pnltri.min.js — you can see that instead of exposing `RNLTRI` global variable, it exposes `r`, and `REVISION` gets mangled into `r.ca`, etc. Probably side effects of Closure Compiler.

I'd highly recommend switching to https://github.com/mishoo/UglifyJS2 — it's fast, robust, written in JS, and can be easily set up through NPM package.json (so that after cloning, a developer can make a build by simply doing `npm install; npm run build`).

**Comment by jahting** [comment]
@mourner sorry for my late reaction ... holidays ...
I'm not sure I get your point. The minified file works fine, e.g. in the example in THREE.JS
Near the end of the file there is e.g. `window.PNLTRI=r;` and some other redefinitions.

I'll look into this NPM thing :-). Since I'm new to JS I've focussed on tests, special cases, size and speed till now.

**Comment by mourner** [comment]
Yeah, you're right — the minified build is fine, sorry for false alarm.
